# Generated by Django 4.0.4 on 2022-07-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrelation',
            name='rate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Normal'), (2, 'Fine'), (3, 'Good'), (4, 'Amazing'), (5, 'Awesome')], null=True),
        ),
    ]
